name: .NET Core

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.101
    - name: Enter Source Folder
      run: cd src/
    - name: Install dependencies
      run: dotnet restore AutoInject.sln
    - name: Build
      run: dotnet build AutoInject.sln --configuration Release --no-restore
    - name: Test
      run: dotnet test AutoInject.sln --no-restore --verbosity normal
